[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = "tools/run-qemu.sh"
rustflags = ["-C", "link-arg=-Tkernel/src/arch/aarch64/linker.ld"]

[target.riscv64gc-unknown-none-elf]
runner = "tools/run-qemu-riscv.sh"
rustflags = ["-C", "link-arg=-Tkernel/src/arch/riscv64/linker.ld"]

[target.x86_64-unknown-none]
runner = "tools/run-qemu-x86.sh"
rustflags = ["-C", "link-arg=-Tkernel/src/arch/x86_64/linker.ld", "-C", "code-model=small", "-C", "relocation-model=static"]

[target.loongarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tkernel/src/arch/loongarch64/linker.ld"]

[target.mips64el-telix-none]
rustflags = ["-C", "link-arg=-Tkernel/src/arch/mips64/linker.ld"]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
