//! GICv3 interrupt controller driver for QEMU virt machine.
//!
//! QEMU virt provides a GICv3 at:
//!   Distributor:   0x0800_0000
//!   Redistributor: 0x080A_0000
//!
//! We use system register access for the CPU interface (ICC_* registers).

// GICD (Distributor) — base discovered from firmware (DTB), QEMU virt fallback.
const GICD_FALLBACK: usize = 0x0800_0000;
fn gicd_base() -> usize {
    let info = crate::firmware::irq_controller();
    if info.kind != 0 {
        info.base0 as usize
    } else {
        GICD_FALLBACK
    }
}

// GICD register offsets
const GICD_CTLR_OFF: usize = 0x000;
const GICD_IGROUPR_OFF: usize = 0x080; // Interrupt Group Registers (SPIs)
const GICD_ISENABLER_OFF: usize = 0x100; // Array of 32-bit registers
const GICD_IPRIORITYR_OFF: usize = 0x400; // Array of 8-bit fields

// GICR (Redistributor) — base discovered from firmware, QEMU virt fallback.
const GICR_FALLBACK: usize = 0x080A_0000;
fn gicr_base() -> usize {
    let info = crate::firmware::irq_controller();
    if info.kind != 0 {
        info.base1 as usize
    } else {
        GICR_FALLBACK
    }
}
const GICR_STRIDE: usize = 0x20000; // 128 KiB per redistributor
const GICR_WAKER_OFFSET: usize = 0x14;
// SGI/PPI redistributor frame is at offset 0x10000 from the redistributor base
const GICR_SGI_BASE_OFFSET: usize = 0x10000;
const GICR_IGROUPR0_OFFSET: usize = 0x080; // Interrupt Group Register 0 (SGIs/PPIs)
const GICR_ISENABLER0_OFFSET: usize = 0x100;
const GICR_IPRIORITYR_OFFSET: usize = 0x400;

// Interrupt IDs
/// SGI 0 — reschedule IPI.  Sent by `send_reschedule_ipi` to wake a
/// CPU that's parked in WFI because its per-CPU runqueue was empty at
/// the last tickless-schedule decision.  The ISR does nothing beyond
/// the EOI and the implicit sched::tick() that runs after every IRQ,
/// which is exactly what we need to pick up newly-enqueued work.
pub const INTID_RESCHEDULE: u32 = 0;
pub const INTID_TIMER_EL1_PHYS: u32 = 30; // PPI: EL1 physical timer (CNTP)
#[allow(dead_code)]
pub const INTID_VIRTIO_BLK: u32 = 48; // SPI: virtio-blk (device at 0x0a003e00)
const INTID_SPURIOUS: u32 = 1023;

/// Initialize the GICv3 redistributor for a specific CPU.
/// Called by secondary CPUs during their init.
pub fn init_cpu(cpu: u32) {
    let gicr_base = gicr_base() + (cpu as usize) * GICR_STRIDE;

    // Wake this CPU's redistributor.
    let waker = (gicr_base + GICR_WAKER_OFFSET) as *mut u32;
    unsafe {
        let val = core::ptr::read_volatile(waker);
        core::ptr::write_volatile(waker, val & !(1 << 1));
        while core::ptr::read_volatile(waker) & (1 << 2) != 0 {
            core::hint::spin_loop();
        }
    }

    // Put all SGIs/PPIs into Group 1.
    let sgi_base = gicr_base + GICR_SGI_BASE_OFFSET;
    unsafe {
        let igroupr0 = (sgi_base + GICR_IGROUPR0_OFFSET) as *mut u32;
        core::ptr::write_volatile(igroupr0, 0xFFFF_FFFF);
    }

    // Configure ICC system registers for this CPU.
    unsafe {
        core::arch::asm!("mrs {tmp}, S3_0_C12_C12_5", "orr {tmp}, {tmp}, #1", "msr S3_0_C12_C12_5, {tmp}", "isb", tmp = out(reg) _);
        core::arch::asm!("mov {tmp}, #0xFF", "msr S3_0_C4_C6_0, {tmp}", tmp = out(reg) _);
        core::arch::asm!("mov {tmp}, #1", "msr S3_0_C12_C12_7, {tmp}", "isb", tmp = out(reg) _);
    }

    // Enable the timer PPI and the reschedule SGI on this CPU's
    // redistributor.  Without the SGI enable, sent IPIs would be
    // generated by the dispatcher but never delivered to this CPU.
    enable_interrupt_on_cpu(INTID_TIMER_EL1_PHYS, gicr_base);
    enable_interrupt_on_cpu(INTID_RESCHEDULE, gicr_base);
}

/// Enable a PPI/SGI on a specific CPU's redistributor.
fn enable_interrupt_on_cpu(intid: u32, gicr_base: usize) {
    if intid < 32 {
        let sgi_base = gicr_base + GICR_SGI_BASE_OFFSET;
        let reg = (sgi_base + GICR_ISENABLER0_OFFSET) as *mut u32;
        unsafe {
            let val = core::ptr::read_volatile(reg);
            core::ptr::write_volatile(reg, val | (1 << intid));
        }
        let prio_reg = (sgi_base + GICR_IPRIORITYR_OFFSET + intid as usize) as *mut u8;
        unsafe {
            core::ptr::write_volatile(prio_reg, 0x80);
        }
    }
}

/// Initialize the GICv3 for the boot CPU (CPU 0).
pub fn init() {
    // 1. Wake the redistributor for CPU 0.
    let gicr_base = gicr_base();
    let waker = (gicr_base + GICR_WAKER_OFFSET) as *mut u32;
    unsafe {
        // Clear ProcessorSleep bit (bit 1).
        let val = core::ptr::read_volatile(waker);
        core::ptr::write_volatile(waker, val & !(1 << 1));
        // Wait until ChildrenAsleep (bit 2) clears.
        while core::ptr::read_volatile(waker) & (1 << 2) != 0 {
            core::hint::spin_loop();
        }
    }

    // 2. Put all SGIs/PPIs (INTID 0-31) into Group 1 (non-secure).
    let sgi_base = gicr_base + GICR_SGI_BASE_OFFSET;
    unsafe {
        let igroupr0 = (sgi_base + GICR_IGROUPR0_OFFSET) as *mut u32;
        core::ptr::write_volatile(igroupr0, 0xFFFF_FFFF); // All Group 1
    }

    // 3. Configure ICC system registers.
    unsafe {
        // ICC_SRE_EL1: Enable system register access (bit 0).
        core::arch::asm!("mrs {tmp}, S3_0_C12_C12_5", "orr {tmp}, {tmp}, #1", "msr S3_0_C12_C12_5, {tmp}", "isb", tmp = out(reg) _);

        // ICC_PMR_EL1: Set priority mask to allow all priorities (0xFF).
        core::arch::asm!("mov {tmp}, #0xFF", "msr S3_0_C4_C6_0, {tmp}", tmp = out(reg) _);

        // ICC_CTLR_EL1: Default config is fine.

        // ICC_IGRPEN1_EL1: Enable Group 1 interrupts (bit 0).
        core::arch::asm!("mov {tmp}, #1", "msr S3_0_C12_C12_7, {tmp}", "isb", tmp = out(reg) _);
    }

    // 3. Put all SPIs (INTID 32..1020) into Group 1 non-secure.
    //    GICD_IGROUPR[0] covers INTIDs 0-31 (SGI/PPI, handled via GICR above).
    //    GICD_IGROUPR[1..32] covers SPIs 32-1023.
    unsafe {
        let gicd = gicd_base();
        for i in 1..32u32 {
            let reg = (gicd + GICD_IGROUPR_OFF + (i as usize) * 4) as *mut u32;
            core::ptr::write_volatile(reg, 0xFFFF_FFFF);
        }
    }

    // 4. Enable the distributor (Group 1 non-secure).
    unsafe {
        let ctlr = (gicd_base() + GICD_CTLR_OFF) as *mut u32;
        // Set EnableGrp1NS (bit 1) and ARE_NS (bit 4).
        core::ptr::write_volatile(ctlr, (1 << 1) | (1 << 4));
    }

    // 5. Enable the reschedule SGI on CPU 0's redistributor.  (Timer
    // comes later via timer::init → enable_interrupt.)  The timer
    // register path reuses this function, so simply calling it again
    // for the SGI works fine.
    enable_interrupt(INTID_RESCHEDULE);

    crate::println!("  GICv3 initialized");
}

/// Enable a specific interrupt ID.
pub fn enable_interrupt(intid: u32) {
    if intid < 32 {
        // PPI/SGI: configure via redistributor for CPU 0.
        let sgi_base = gicr_base() + GICR_SGI_BASE_OFFSET;
        let reg = (sgi_base + GICR_ISENABLER0_OFFSET) as *mut u32;
        unsafe {
            let val = core::ptr::read_volatile(reg);
            core::ptr::write_volatile(reg, val | (1 << intid));
        }
        // Set priority (lower number = higher priority). Use 0x80.
        let prio_reg = (sgi_base + GICR_IPRIORITYR_OFFSET + intid as usize) as *mut u8;
        unsafe {
            core::ptr::write_volatile(prio_reg, 0x80);
        }
    } else {
        // SPI: configure via distributor.
        let gicd = gicd_base();
        let reg_index = (intid / 32) as usize;
        let bit = intid % 32;
        let reg = (gicd + GICD_ISENABLER_OFF + reg_index * 4) as *mut u32;
        unsafe {
            core::ptr::write_volatile(reg, 1 << bit);
        }
        // Set priority.
        let prio_reg = (gicd + GICD_IPRIORITYR_OFF + intid as usize) as *mut u8;
        unsafe {
            core::ptr::write_volatile(prio_reg, 0x80);
        }
        // DSB+ISB: ensure the GIC distributor write is complete and visible
        // before the CPU proceeds. Without this, an immediate irq_wait()
        // can race with the GIC configuration, losing the first interrupt.
        unsafe {
            core::arch::asm!("dsb sy", "isb");
        }
        // Route to CPU 0 (GICD_IROUTER default is fine for GICv3 with ARE).
    }
}

/// Acknowledge the highest-priority pending interrupt. Returns the interrupt ID.
pub fn acknowledge() -> u32 {
    let intid: u64;
    unsafe {
        // ICC_IAR1_EL1
        core::arch::asm!("mrs {}, S3_0_C12_C12_0", out(reg) intid);
    }
    intid as u32
}

/// Signal end-of-interrupt for the given interrupt ID.
pub fn end_of_interrupt(intid: u32) {
    unsafe {
        // ICC_EOIR1_EL1
        core::arch::asm!("msr S3_0_C12_C12_1, {}", in(reg) intid as u64);
    }
}

/// Send INTID_RESCHEDULE to `target_cpu` via ICC_SGI1R_EL1.
///
/// The write's encoding (ARMv8-A A-profile B4.1.114):
///   bits[15:0]  = TargetList (bitmap of Aff0 within the affinity group)
///   bits[27:24] = INTID (SGI number 0..15)
///   bits[23:16] = Aff1
///   bits[39:32] = Aff2
///   bits[55:48] = Aff3
///   bits[40]    = IRM (0 = target list, 1 = all CPUs except self)
///
/// For QEMU's `virt` machine with `-cpu cortex-a72`, Aff1-3 are all zero
/// and cpu_id == Aff0, so target_list = 1 << target_cpu is sufficient.
/// Extend here if we ever run on a multi-cluster platform.
pub fn send_sgi(target_cpu: u32, sgi_id: u32) {
    debug_assert!(sgi_id < 16, "SGI id out of range");
    let target_list: u64 = 1u64 << (target_cpu & 0x0F);
    let value: u64 = target_list | ((sgi_id as u64 & 0xF) << 24);
    unsafe {
        // ICC_SGI1R_EL1
        core::arch::asm!(
            "msr S3_0_C12_C11_5, {val}",
            "isb",
            val = in(reg) value,
        );
    }
    SGI_SEND_COUNT.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
}

pub static SGI_SEND_COUNT: core::sync::atomic::AtomicU64 =
    core::sync::atomic::AtomicU64::new(0);
pub static SGI_RECV_COUNT: core::sync::atomic::AtomicU64 =
    core::sync::atomic::AtomicU64::new(0);

/// Top-level IRQ handler called from exception vectors.
pub fn handle_irq() {
    let intid = acknowledge();
    if intid == INTID_SPURIOUS {
        return;
    }

    match intid {
        INTID_RESCHEDULE => {
            // The SGI itself carries no payload — its only job is to
            // wake this CPU out of WFI so the caller of handle_irq
            // (exception_irq_el1) can run sched::tick(), which picks
            // up any newly-enqueued work on this CPU's runqueue.
            SGI_RECV_COUNT
                .fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        }
        INTID_TIMER_EL1_PHYS => {
            crate::arch::aarch64::timer::handle_timer_irq();
        }
        // Virtio-mmio devices: INTID 48-79 (SPI 16-47, 32 devices on QEMU virt)
        48..=79 => {
            // Try userspace dispatch first; fall back to kernel driver.
            if !crate::io::irq_dispatch::handle_irq(intid) {
                crate::drivers::virtio_blk::irq_handler();
            }
        }
        _ => {
            crate::println!("Unhandled IRQ: {}", intid);
        }
    }

    end_of_interrupt(intid);
}
